
services:
  relatorio-api:
    build: .
    container_name: relatorio-export-api
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - relatorio-network

networks:
  relatorio-network:
    driver: bridge